[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
